x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.nanobot:/home/nanobot/.nanobot
  cap_drop:
    - ALL
  cap_add:
    - SYS_ADMIN
  security_opt:
    - apparmor=unconfined
    - seccomp=unconfined

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18790:18790
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M

  nanobot-api:
    container_name: nanobot-api
    <<: *common-config
    command:
      ["serve", "--host", "0.0.0.0", "-w", "/home/nanobot/.nanobot/api-workspace"]
    restart: unless-stopped
    ports:
      - 127.0.0.1:8900:8900
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M

  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true

  nanobot-web:
    container_name: nanobot-web
    image: nanobot-http-test:latest
    restart: unless-stopped
    ports:
      - "18798:18792"
      - "18799:18791"
    volumes:
      - ./nanobot:/app/nanobot
      - ./http_api:/app/http_api
      - ./.nanobot:/root/.nanobot
      - ./tests:/app/tests
    env_file:
      - .env
    command: bash -c "cd /app && nohup python -m nanobot gateway > /app/gateway.log 2>&1 & echo 'Gateway started' && exec python -m uvicorn http_api.main:app --host 0.0.0.0 --port 18792"

  nanobots:
    container_name: nanobots
    image: nanobot-http-test:latest
    restart: unless-stopped
    # ports:
    #   - "18798:18792"
    #   - "18799:18791"
    volumes:
      - ./.nanobots:/app/.nanobots
      - ./http_api:/app/http_api
      - ./nanobot:/app/nanobot
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
      - ./start_gateway.sh:/app/start_gateway.sh
      - ./logs:/app/logs
    env_file:
      - .env
    # command: bash -c "cd /app python -m nan python -m nanobot gateway > /app/gateway.log 2>&1 & echo 'Gateway started' && exec python -m uvicorn http_api.main:app --host 0.0.0.0 --port 18792"
    command: bash -c "pip install --no-cache-dir -e . && tail -f /dev/null"
